name: pos_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.1
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.2
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  supabase: ^1.5.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
